# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ImageSearchExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageSearchExample

  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxCocoa'
  pod 'RxViewController'
  pod 'RxOptional'
  pod 'RxDataSources'
  pod 'RxFlow'
  
  # Network
  pod 'Alamofire'

  # Image
  pod 'Kingfisher'

  # Other
  pod 'SwiftLint'

  target 'ImageSearchExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
  end

end
