# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ImageSearchExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageSearchExample

  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RxDataSources'

  # Network
  pod 'Alamofire', '~> 5.2'

  # Image
  pod 'Kingfisher', '~> 5.0'

  # Other
  pod 'SwiftLint'
  pod 'SCoordinator'

  target 'ImageSearchExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
